---
image: docker.input-output.dk/docker/nodejs:7.5.0

stages:
  - prepare
  - verify
  - build

yarn:install:
  cache:
    paths:
      - node_modules/
  stage: prepare
  script:
    - yarn install --ignore-scripts
  tags:
    - kubernetes
  artifacts:
    paths:
      - node_modules/

test:nodejs:7.5.0:
  stage: verify
  image: docker.input-output.dk/docker/nodejs:7.5.0
  dependencies:
    - yarn:install
  script:
    - yarn test
  tags:
    - kubernetes
    
test:nodejs:6.9.5:
  stage: verify
  image: docker.input-output.dk/docker/nodejs:6.9.5
  dependencies:
    - yarn:install
  script:
    - yarn test
  tags:
    - kubernetes

lint:
  stage: verify
  dependencies:
    - yarn:install
  script:
    - yarn lint
  tags:
    - kubernetes

build:
  stage: build
  dependencies:
    - yarn:install
  script:
    - yarn build
  artifacts:
    paths:
      - lib/
  tags:
    - kubernetes
