---
image: docker.input-output.dk/docker/nodejs:7.5.0

stages:
  - prepare
  - verify
  - build
  - publish:pages

yarn:install:
  cache:
    paths:
      - node_modules/
  stage: prepare
  script:
    - yarn install --ignore-scripts
  tags:
    - kubernetes
  artifacts:
    paths:
      - node_modules/

test:nodejs:7.5.0:
  stage: verify
  image: docker.input-output.dk/docker/nodejs:7.5.0
  dependencies:
    - yarn:install
  script:
    - yarn test
  tags:
    - kubernetes

test:nodejs:6.9.5:
  stage: verify
  image: docker.input-output.dk/docker/nodejs:6.9.5
  dependencies:
    - yarn:install
  script:
    - yarn test
  tags:
    - kubernetes

test:nodejs:4.7.3:
  stage: verify
  image: docker.input-output.dk/docker/nodejs:4.7.3
  dependencies:
    - yarn:install
  script:
    - yarn test
  tags:
    - kubernetes

lint:
  stage: verify
  dependencies:
    - yarn:install
  script:
    - yarn lint
  tags:
    - kubernetes

build:
  stage: build
  dependencies:
    - yarn:install
  script:
    - yarn build
  artifacts:
    paths:
      - lib/
  tags:
    - kubernetes

pages:
  image: docker.input-output.dk/docker/nodejs:7.5.0
  cache:
    paths:
      - docs/node_modules
  stage: publish:pages
  script:
    - mkdir public/
    - echo "<html><head><title>graphql-fragment-type-generator</title></head><body><h1>Comming soon</h1></body></html>" > public/index.html
  tags:
    - kubernetes
  only:
    - master
  artifacts:
    paths:
      - public/
